(()=>{const c=document.querySelector('#game'),x=c.getContext('2d'),overlay=document.querySelector('#overlay'),start=document.querySelector('#start'),waveLabel=document.querySelector('#wave'),scoreLabel=document.querySelector('#score');let run=false,wave=1,score=0,keys={},drag=null,last=0,hero={x:220,y:520,hp:100,cd:0},enemies=[],shots=[],sparks=[],choices=[];const W=440,H=640;
const powers=[['Flamme jumelle','Deux projectiles à chaque tir.'],['Cœur de braise','Tes dégâts augmentent fortement.'],['Souffle léger','Déplacement plus rapide.']];let power=0,damage=17,speed=170,rate=.48,shotCount=1;
function reset(){wave=1;score=0;power=0;damage=17;speed=170;rate=.48;shotCount=1;hero={x:220,y:520,hp:100,cd:0};shots=[];sparks=[];spawn();updateHud()}
function spawn(){enemies=[];for(let i=0;i<3+wave*2;i++){let t=i%3;enemies.push({x:55+(i%4)*108,y:120+Math.floor(i/4)*68,hp:t===2?55+wave*8:32+wave*6,r:t===2?23:15,t,cd:1+Math.random()*1.5})}if(wave===5)enemies=[{x:220,y:120,hp:620,r:42,t:3,cd:1.6}]}
function updateHud(){waveLabel.textContent=`LANTERNE · VAGUE ${wave}/5`;scoreLabel.textContent=`${score} ✦`}
function startGame(){reset();run=true;overlay.classList.add('hidden');last=performance.now();requestAnimationFrame(loop)}
function upgrade(){run=false;choices=[...powers].sort(()=>Math.random()-.5).slice(0,3);overlay.innerHTML='<div class="card"><div class="eyebrow">VAGUE TRAVERSÉE</div><div class="title" style="font-size:36px">Fais grandir ta lumière</div><p class="sub">Choisis un don pour la suite du voyage.</p><div class="choices">'+choices.map((p,i)=>`<button class="choice" data-i="${i}"><b>${p[0]}</b><span>${p[1]}</span></button>`).join('')+'</div></div>';overlay.classList.remove('hidden');overlay.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{const i=+b.dataset.i;power++;if(i===0)shotCount++;if(i===1)damage*=1.4;if(i===2)speed*=1.2;wave++;spawn();overlay.classList.add('hidden');run=true;last=performance.now();requestAnimationFrame(loop);updateHud()})}
function end(win){run=false;overlay.innerHTML=`<div class="card"><div class="eyebrow">${win?'LE JARDIN RESPIRE À NOUVEAU':'LA NUIT A GAGNÉ CETTE FOIS'}</div><div class="title" style="font-size:38px">${win?'La lumière est revenue.':'Une braise suffit à renaître.'}</div><p class="sub">${score} éclats de lumière · ${wave===5?'Boss vaincu':'Vague '+wave}</p><button class="button" id="again">Rallumer la lanterne</button></div>`;overlay.classList.remove('hidden');document.querySelector('#again').onclick=startGame}
function unit(a,b){let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1;return{x:dx/d,y:dy/d}}
function burst(p,col='#ffd18a'){for(let i=0;i<8;i++){let a=Math.random()*6.28;sparks.push({x:p.x,y:p.y,vx:Math.cos(a)*60,vy:Math.sin(a)*60,l:1,col})}}
function step(dt){let dx=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0),dy=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0);if(drag){dx=drag.dx;dy=drag.dy}let m=Math.hypot(dx,dy)||1;if(dx||dy){hero.x=Math.max(35,Math.min(405,hero.x+dx/m*speed*dt));hero.y=Math.max(90,Math.min(580,hero.y+dy/m*speed*dt))}hero.cd-=dt;if(!dx&&!dy&&hero.cd<=0&&enemies.length){let e=enemies.reduce((a,b)=>(a.x-hero.x)**2+(a.y-hero.y)**2<(b.x-hero.x)**2+(b.y-hero.y)**2?a:b);let a=Math.atan2(e.y-hero.y,e.x-hero.x);for(let i=0;i<shotCount;i++){let q=a+(i-(shotCount-1)/2)*.12;shots.push({x:hero.x,y:hero.y,vx:Math.cos(q)*340,vy:Math.sin(q)*340,d:damage,l:3})}hero.cd=rate}
enemies.forEach(e=>{let d=unit(e,hero);if(e.t===1){e.cd-=dt;if(e.cd<0){shots.push({x:e.x,y:e.y,vx:d.x*120,vy:d.y*120,d:10,hostile:true,l:5});e.cd=2.3}}else{e.x+=d.x*(e.t===3?16:32)*dt;e.y+=d.y*(e.t===3?16:32)*dt}if(Math.hypot(e.x-hero.x,e.y-hero.y)<e.r+12&&hero.inv<0){hero.hp-=e.t===3?18:10;hero.inv=.8;burst(hero,'#ff938c');if(hero.hp<=0)end(false)}});hero.inv=(hero.inv||0)-dt;
shots.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt;s.l-=dt;if(s.x<20||s.x>420||s.y<70||s.y>610)s.l=0;if(s.hostile&&Math.hypot(s.x-hero.x,s.y-hero.y)<14){s.l=0;hero.hp-=s.d;hero.inv=.8;if(hero.hp<=0)end(false)}if(!s.hostile)enemies.forEach(e=>{if(e.hp>0&&Math.hypot(s.x-e.x,s.y-e.y)<e.r+5){e.hp-=s.d;s.l=0;burst({x:s.x,y:s.y})}})});shots=shots.filter(s=>s.l>0);enemies.forEach(e=>{if(e.hp<=0){score+=e.t===3?250:25;burst(e,'#8de1c2')}});enemies=enemies.filter(e=>e.hp>0);sparks.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt;s.l-=dt*2});sparks=sparks.filter(s=>s.l>0);if(!enemies.length){if(wave===5)end(true);else upgrade()}updateHud()}
function draw(){let g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,'#162f38');g.addColorStop(1,'#183e3c');x.fillStyle=g;x.fillRect(0,0,W,H);x.fillStyle='#284a43';x.fillRect(22,70,396,540);for(let y=75;y<610;y+=46)for(let q=35;q<420;q+=72){x.fillStyle=(q/72+y/46%2)%2?'#304d45':'#2a4640';x.fillRect(q,y,66,42)}x.strokeStyle='#2e7e69';x.globalAlpha=.35;x.beginPath();x.arc(220,325,95,0,7);x.stroke();x.globalAlpha=1;for(let i=0;i<4;i++){let a=performance.now()/1800+i*1.57;x.fillStyle='#8de1c2';x.shadowBlur=18;x.shadowColor='#8de1c2';x.beginPath();x.arc(220+Math.cos(a)*145,330+Math.sin(a)*190,3,0,7);x.fill()}x.shadowBlur=0;enemies.forEach(e=>{x.save();x.translate(e.x,e.y);x.fillStyle=e.t===0?'#ad759d':e.t===1?'#858bbc':e.t===2?'#477d79':'#557f70';x.beginPath();x.ellipse(0,0,e.r,e.r*.8,0,0,7);x.fill();x.fillStyle='#ffe1a5';x.beginPath();x.arc(-5,-3,2,0,7);x.arc(5,-3,2,0,7);x.fill();x.restore()});shots.forEach(s=>{x.fillStyle=s.hostile?'#ff938c':'#ffd18a';x.shadowBlur=16;x.shadowColor=x.fillStyle;x.beginPath();x.arc(s.x,s.y,4,0,7);x.fill();x.shadowBlur=0});sparks.forEach(s=>{x.globalAlpha=Math.max(0,s.l);x.fillStyle=s.col;x.fillRect(s.x,s.y,3,3)});x.globalAlpha=1;x.save();x.translate(hero.x,hero.y);x.fillStyle='#da9971';x.beginPath();x.moveTo(-14,10);x.quadraticCurveTo(-18,-12,0,-22);x.quadraticCurveTo(18,-12,14,10);x.fill();x.fillStyle='#263d43';x.beginPath();x.arc(0,-23,17,0,7);x.fill();x.fillStyle='#f9e8c2';x.beginPath();x.arc(0,-21,9,0,7);x.fill();x.fillStyle='#ffd18a';x.fillRect(15,-24,12,16);x.restore();x.fillStyle='#8de1c2';x.fillRect(35,45,130*hero.hp/100,5);x.strokeStyle='#71958a';x.strokeRect(35,45,130,5)}
function loop(t){if(!run)return;let dt=Math.min(.04,(t-last)/1000);last=t;step(dt);draw();requestAnimationFrame(loop)}
addEventListener('keydown',e=>{keys[e.key]=true});addEventListener('keyup',e=>{keys[e.key]=false});c.addEventListener('pointerdown',e=>{c.setPointerCapture(e.pointerId);drag={x:0,y:0,ox:e.clientX,oy:e.clientY}});c.addEventListener('pointermove',e=>{if(!drag)return;let dx=e.clientX-drag.ox,dy=e.clientY-drag.oy,d=Math.hypot(dx,dy)||1;drag.dx=dx/d;drag.dy=dy/d});c.addEventListener('pointerup',()=>drag=null);start.onclick=startGame;draw()})();

